# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ishaysela/projects/lightningPlusPlus/unit-tests

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ishaysela/projects/lightningPlusPlus/unit-tests/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(CMAKE_COMMAND) -E cmake_progress_start /home/ishaysela/projects/lightningPlusPlus/unit-tests/build/CMakeFiles /home/ishaysela/projects/lightningPlusPlus//CMakeFiles/progress.marks
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ../../all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ishaysela/projects/lightningPlusPlus/unit-tests/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ../../clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ../../preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ../../preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
../..//CMakeFiles/http.dir/rule:
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ../..//CMakeFiles/http.dir/rule
.PHONY : ../..//CMakeFiles/http.dir/rule

# Convenience name for target.
http: ../..//CMakeFiles/http.dir/rule
.PHONY : http

# fast build rule for target.
http/fast:
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(MAKE) $(MAKESILENT) -f ../..//CMakeFiles/http.dir/build.make ../..//CMakeFiles/http.dir/build
.PHONY : http/fast

HttpRequest.o: HttpRequest.cpp.o
.PHONY : HttpRequest.o

# target to build an object file
HttpRequest.cpp.o:
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(MAKE) $(MAKESILENT) -f ../..//CMakeFiles/http.dir/build.make ../..//CMakeFiles/http.dir/HttpRequest.cpp.o
.PHONY : HttpRequest.cpp.o

HttpRequest.i: HttpRequest.cpp.i
.PHONY : HttpRequest.i

# target to preprocess a source file
HttpRequest.cpp.i:
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(MAKE) $(MAKESILENT) -f ../..//CMakeFiles/http.dir/build.make ../..//CMakeFiles/http.dir/HttpRequest.cpp.i
.PHONY : HttpRequest.cpp.i

HttpRequest.s: HttpRequest.cpp.s
.PHONY : HttpRequest.s

# target to generate assembly for a file
HttpRequest.cpp.s:
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(MAKE) $(MAKESILENT) -f ../..//CMakeFiles/http.dir/build.make ../..//CMakeFiles/http.dir/HttpRequest.cpp.s
.PHONY : HttpRequest.cpp.s

HttpResponse.o: HttpResponse.cpp.o
.PHONY : HttpResponse.o

# target to build an object file
HttpResponse.cpp.o:
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(MAKE) $(MAKESILENT) -f ../..//CMakeFiles/http.dir/build.make ../..//CMakeFiles/http.dir/HttpResponse.cpp.o
.PHONY : HttpResponse.cpp.o

HttpResponse.i: HttpResponse.cpp.i
.PHONY : HttpResponse.i

# target to preprocess a source file
HttpResponse.cpp.i:
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(MAKE) $(MAKESILENT) -f ../..//CMakeFiles/http.dir/build.make ../..//CMakeFiles/http.dir/HttpResponse.cpp.i
.PHONY : HttpResponse.cpp.i

HttpResponse.s: HttpResponse.cpp.s
.PHONY : HttpResponse.s

# target to generate assembly for a file
HttpResponse.cpp.s:
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(MAKE) $(MAKESILENT) -f ../..//CMakeFiles/http.dir/build.make ../..//CMakeFiles/http.dir/HttpResponse.cpp.s
.PHONY : HttpResponse.cpp.s

HttpResponseBuilder.o: HttpResponseBuilder.cpp.o
.PHONY : HttpResponseBuilder.o

# target to build an object file
HttpResponseBuilder.cpp.o:
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(MAKE) $(MAKESILENT) -f ../..//CMakeFiles/http.dir/build.make ../..//CMakeFiles/http.dir/HttpResponseBuilder.cpp.o
.PHONY : HttpResponseBuilder.cpp.o

HttpResponseBuilder.i: HttpResponseBuilder.cpp.i
.PHONY : HttpResponseBuilder.i

# target to preprocess a source file
HttpResponseBuilder.cpp.i:
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(MAKE) $(MAKESILENT) -f ../..//CMakeFiles/http.dir/build.make ../..//CMakeFiles/http.dir/HttpResponseBuilder.cpp.i
.PHONY : HttpResponseBuilder.cpp.i

HttpResponseBuilder.s: HttpResponseBuilder.cpp.s
.PHONY : HttpResponseBuilder.s

# target to generate assembly for a file
HttpResponseBuilder.cpp.s:
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(MAKE) $(MAKESILENT) -f ../..//CMakeFiles/http.dir/build.make ../..//CMakeFiles/http.dir/HttpResponseBuilder.cpp.s
.PHONY : HttpResponseBuilder.cpp.s

HttpServer.o: HttpServer.cpp.o
.PHONY : HttpServer.o

# target to build an object file
HttpServer.cpp.o:
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(MAKE) $(MAKESILENT) -f ../..//CMakeFiles/http.dir/build.make ../..//CMakeFiles/http.dir/HttpServer.cpp.o
.PHONY : HttpServer.cpp.o

HttpServer.i: HttpServer.cpp.i
.PHONY : HttpServer.i

# target to preprocess a source file
HttpServer.cpp.i:
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(MAKE) $(MAKESILENT) -f ../..//CMakeFiles/http.dir/build.make ../..//CMakeFiles/http.dir/HttpServer.cpp.i
.PHONY : HttpServer.cpp.i

HttpServer.s: HttpServer.cpp.s
.PHONY : HttpServer.s

# target to generate assembly for a file
HttpServer.cpp.s:
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(MAKE) $(MAKESILENT) -f ../..//CMakeFiles/http.dir/build.make ../..//CMakeFiles/http.dir/HttpServer.cpp.s
.PHONY : HttpServer.cpp.s

LowLevelApiException.o: LowLevelApiException.cpp.o
.PHONY : LowLevelApiException.o

# target to build an object file
LowLevelApiException.cpp.o:
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(MAKE) $(MAKESILENT) -f ../..//CMakeFiles/http.dir/build.make ../..//CMakeFiles/http.dir/LowLevelApiException.cpp.o
.PHONY : LowLevelApiException.cpp.o

LowLevelApiException.i: LowLevelApiException.cpp.i
.PHONY : LowLevelApiException.i

# target to preprocess a source file
LowLevelApiException.cpp.i:
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(MAKE) $(MAKESILENT) -f ../..//CMakeFiles/http.dir/build.make ../..//CMakeFiles/http.dir/LowLevelApiException.cpp.i
.PHONY : LowLevelApiException.cpp.i

LowLevelApiException.s: LowLevelApiException.cpp.s
.PHONY : LowLevelApiException.s

# target to generate assembly for a file
LowLevelApiException.cpp.s:
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(MAKE) $(MAKESILENT) -f ../..//CMakeFiles/http.dir/build.make ../..//CMakeFiles/http.dir/LowLevelApiException.cpp.s
.PHONY : LowLevelApiException.cpp.s

SSLClient.o: SSLClient.cpp.o
.PHONY : SSLClient.o

# target to build an object file
SSLClient.cpp.o:
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(MAKE) $(MAKESILENT) -f ../..//CMakeFiles/http.dir/build.make ../..//CMakeFiles/http.dir/SSLClient.cpp.o
.PHONY : SSLClient.cpp.o

SSLClient.i: SSLClient.cpp.i
.PHONY : SSLClient.i

# target to preprocess a source file
SSLClient.cpp.i:
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(MAKE) $(MAKESILENT) -f ../..//CMakeFiles/http.dir/build.make ../..//CMakeFiles/http.dir/SSLClient.cpp.i
.PHONY : SSLClient.cpp.i

SSLClient.s: SSLClient.cpp.s
.PHONY : SSLClient.s

# target to generate assembly for a file
SSLClient.cpp.s:
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(MAKE) $(MAKESILENT) -f ../..//CMakeFiles/http.dir/build.make ../..//CMakeFiles/http.dir/SSLClient.cpp.s
.PHONY : SSLClient.cpp.s

SSLServer.o: SSLServer.cpp.o
.PHONY : SSLServer.o

# target to build an object file
SSLServer.cpp.o:
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(MAKE) $(MAKESILENT) -f ../..//CMakeFiles/http.dir/build.make ../..//CMakeFiles/http.dir/SSLServer.cpp.o
.PHONY : SSLServer.cpp.o

SSLServer.i: SSLServer.cpp.i
.PHONY : SSLServer.i

# target to preprocess a source file
SSLServer.cpp.i:
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(MAKE) $(MAKESILENT) -f ../..//CMakeFiles/http.dir/build.make ../..//CMakeFiles/http.dir/SSLServer.cpp.i
.PHONY : SSLServer.cpp.i

SSLServer.s: SSLServer.cpp.s
.PHONY : SSLServer.s

# target to generate assembly for a file
SSLServer.cpp.s:
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(MAKE) $(MAKESILENT) -f ../..//CMakeFiles/http.dir/build.make ../..//CMakeFiles/http.dir/SSLServer.cpp.s
.PHONY : SSLServer.cpp.s

SSLStream.o: SSLStream.cpp.o
.PHONY : SSLStream.o

# target to build an object file
SSLStream.cpp.o:
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(MAKE) $(MAKESILENT) -f ../..//CMakeFiles/http.dir/build.make ../..//CMakeFiles/http.dir/SSLStream.cpp.o
.PHONY : SSLStream.cpp.o

SSLStream.i: SSLStream.cpp.i
.PHONY : SSLStream.i

# target to preprocess a source file
SSLStream.cpp.i:
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(MAKE) $(MAKESILENT) -f ../..//CMakeFiles/http.dir/build.make ../..//CMakeFiles/http.dir/SSLStream.cpp.i
.PHONY : SSLStream.cpp.i

SSLStream.s: SSLStream.cpp.s
.PHONY : SSLStream.s

# target to generate assembly for a file
SSLStream.cpp.s:
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(MAKE) $(MAKESILENT) -f ../..//CMakeFiles/http.dir/build.make ../..//CMakeFiles/http.dir/SSLStream.cpp.s
.PHONY : SSLStream.cpp.s

SmartResource.o: SmartResource.cpp.o
.PHONY : SmartResource.o

# target to build an object file
SmartResource.cpp.o:
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(MAKE) $(MAKESILENT) -f ../..//CMakeFiles/http.dir/build.make ../..//CMakeFiles/http.dir/SmartResource.cpp.o
.PHONY : SmartResource.cpp.o

SmartResource.i: SmartResource.cpp.i
.PHONY : SmartResource.i

# target to preprocess a source file
SmartResource.cpp.i:
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(MAKE) $(MAKESILENT) -f ../..//CMakeFiles/http.dir/build.make ../..//CMakeFiles/http.dir/SmartResource.cpp.i
.PHONY : SmartResource.cpp.i

SmartResource.s: SmartResource.cpp.s
.PHONY : SmartResource.s

# target to generate assembly for a file
SmartResource.cpp.s:
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(MAKE) $(MAKESILENT) -f ../..//CMakeFiles/http.dir/build.make ../..//CMakeFiles/http.dir/SmartResource.cpp.s
.PHONY : SmartResource.cpp.s

StaticFile.o: StaticFile.cpp.o
.PHONY : StaticFile.o

# target to build an object file
StaticFile.cpp.o:
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(MAKE) $(MAKESILENT) -f ../..//CMakeFiles/http.dir/build.make ../..//CMakeFiles/http.dir/StaticFile.cpp.o
.PHONY : StaticFile.cpp.o

StaticFile.i: StaticFile.cpp.i
.PHONY : StaticFile.i

# target to preprocess a source file
StaticFile.cpp.i:
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(MAKE) $(MAKESILENT) -f ../..//CMakeFiles/http.dir/build.make ../..//CMakeFiles/http.dir/StaticFile.cpp.i
.PHONY : StaticFile.cpp.i

StaticFile.s: StaticFile.cpp.s
.PHONY : StaticFile.s

# target to generate assembly for a file
StaticFile.cpp.s:
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(MAKE) $(MAKESILENT) -f ../..//CMakeFiles/http.dir/build.make ../..//CMakeFiles/http.dir/StaticFile.cpp.s
.PHONY : StaticFile.cpp.s

Strings.o: Strings.cpp.o
.PHONY : Strings.o

# target to build an object file
Strings.cpp.o:
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(MAKE) $(MAKESILENT) -f ../..//CMakeFiles/http.dir/build.make ../..//CMakeFiles/http.dir/Strings.cpp.o
.PHONY : Strings.cpp.o

Strings.i: Strings.cpp.i
.PHONY : Strings.i

# target to preprocess a source file
Strings.cpp.i:
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(MAKE) $(MAKESILENT) -f ../..//CMakeFiles/http.dir/build.make ../..//CMakeFiles/http.dir/Strings.cpp.i
.PHONY : Strings.cpp.i

Strings.s: Strings.cpp.s
.PHONY : Strings.s

# target to generate assembly for a file
Strings.cpp.s:
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(MAKE) $(MAKESILENT) -f ../..//CMakeFiles/http.dir/build.make ../..//CMakeFiles/http.dir/Strings.cpp.s
.PHONY : Strings.cpp.s

UriMapper.o: UriMapper.cpp.o
.PHONY : UriMapper.o

# target to build an object file
UriMapper.cpp.o:
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(MAKE) $(MAKESILENT) -f ../..//CMakeFiles/http.dir/build.make ../..//CMakeFiles/http.dir/UriMapper.cpp.o
.PHONY : UriMapper.cpp.o

UriMapper.i: UriMapper.cpp.i
.PHONY : UriMapper.i

# target to preprocess a source file
UriMapper.cpp.i:
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(MAKE) $(MAKESILENT) -f ../..//CMakeFiles/http.dir/build.make ../..//CMakeFiles/http.dir/UriMapper.cpp.i
.PHONY : UriMapper.cpp.i

UriMapper.s: UriMapper.cpp.s
.PHONY : UriMapper.s

# target to generate assembly for a file
UriMapper.cpp.s:
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(MAKE) $(MAKESILENT) -f ../..//CMakeFiles/http.dir/build.make ../..//CMakeFiles/http.dir/UriMapper.cpp.s
.PHONY : UriMapper.cpp.s

sockets.o: sockets.cpp.o
.PHONY : sockets.o

# target to build an object file
sockets.cpp.o:
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(MAKE) $(MAKESILENT) -f ../..//CMakeFiles/http.dir/build.make ../..//CMakeFiles/http.dir/sockets.cpp.o
.PHONY : sockets.cpp.o

sockets.i: sockets.cpp.i
.PHONY : sockets.i

# target to preprocess a source file
sockets.cpp.i:
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(MAKE) $(MAKESILENT) -f ../..//CMakeFiles/http.dir/build.make ../..//CMakeFiles/http.dir/sockets.cpp.i
.PHONY : sockets.cpp.i

sockets.s: sockets.cpp.s
.PHONY : sockets.s

# target to generate assembly for a file
sockets.cpp.s:
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(MAKE) $(MAKESILENT) -f ../..//CMakeFiles/http.dir/build.make ../..//CMakeFiles/http.dir/sockets.cpp.s
.PHONY : sockets.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... http"
	@echo "... HttpRequest.o"
	@echo "... HttpRequest.i"
	@echo "... HttpRequest.s"
	@echo "... HttpResponse.o"
	@echo "... HttpResponse.i"
	@echo "... HttpResponse.s"
	@echo "... HttpResponseBuilder.o"
	@echo "... HttpResponseBuilder.i"
	@echo "... HttpResponseBuilder.s"
	@echo "... HttpServer.o"
	@echo "... HttpServer.i"
	@echo "... HttpServer.s"
	@echo "... LowLevelApiException.o"
	@echo "... LowLevelApiException.i"
	@echo "... LowLevelApiException.s"
	@echo "... SSLClient.o"
	@echo "... SSLClient.i"
	@echo "... SSLClient.s"
	@echo "... SSLServer.o"
	@echo "... SSLServer.i"
	@echo "... SSLServer.s"
	@echo "... SSLStream.o"
	@echo "... SSLStream.i"
	@echo "... SSLStream.s"
	@echo "... SmartResource.o"
	@echo "... SmartResource.i"
	@echo "... SmartResource.s"
	@echo "... StaticFile.o"
	@echo "... StaticFile.i"
	@echo "... StaticFile.s"
	@echo "... Strings.o"
	@echo "... Strings.i"
	@echo "... Strings.s"
	@echo "... UriMapper.o"
	@echo "... UriMapper.i"
	@echo "... UriMapper.s"
	@echo "... sockets.o"
	@echo "... sockets.i"
	@echo "... sockets.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/ishaysela/projects/lightningPlusPlus/unit-tests/build && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

